site_name: 芯之联文档中心
repo_url: https://github.com/XradioTech/xradiotech.github.io
site_favicon: XRADIOTECHLOGO.ico
logo: images/XRADIOTECHLOGO.png
nav:
    - 文档主页: index.md
    - 快速入门: zh_CN/get-started/get-started.md
    - 产品手册: zh_CN/ic-doc/index.md
    - 硬件参考: zh_CN/hardware-reference/index.md
    - 软件指南: zh_CN/software-guide/index.md
    - API参考: zh_CN/api-reference/index.md
    - 产品设计: zh_CN/product-design-guide/index.md
    - 生产测试: zh_CN/manufature-test/index.md
    - 认证指导: zh_CN/certification/index.md
    - 工程报告: zh_CN/reports/index.md
theme: readthedocs
