site_name: 芯之联文档中心
logo: images/XRADIOTECHLOGO.png
pages:
    - ['zh_CN/get-started/index.md', '快速入门']
        - ['zh_CN/get-started/index.md#准备工作', '准备工作']
            - ['zh_CN/get-started/index.md#了解硬件', '1. 了解硬件']

theme: readthedocs
article_nav_bottom: true
